### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by badcat** [hasinhayder/wordle-alpinejs#1]
Maybe I don't even understand how to play the game... but this doesn't seem like how it should work.

![wordler](https://user-images.githubusercontent.com/26096/152579393-4f1e8cc0-4ee8-4674-b67c-01ca87b6677d.png)

**Comment by RasheedAZ** [comment]
I tried this on Firefox and then on Chrome, both on desktop, but nothing shows up - not letters, any text or buttons...

**Comment by badcat** [comment]
Try lowercase letters?

**Comment by hasinhayder** [comment]
Just type, you dont need to select anything. There is a keydown event attached to the body of this page which will capture your keystroke without issues,.

**Comment by RasheedAZ** [comment]
Okay. It does work. Thanks. Sorry didn't know you just have to type - I thought it should say something first, instructions, etc.
